CollegeApp/Models/Subject.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CollegeApp.Models
{
    public class Subject
    {
 
        [Key]
        public int Id { get; set; }
        [Required]
        [Display(Name = "Subject Title")]
        public string? SubjectTitle { get; set; }
        public int CourseId { get; set; }



        //Relationships
        public virtual ICollection<Student>? Students { get; set; }

        public Course? Course { get; set; }
        public virtual Teacher? Teacher { get; set; }
        public virtual ICollection<Grade>? Grades { get; set; }


    }
}

CollegeApp/Controllers/SubjectController.cs
using CollegeApp.Data;
using CollegeApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CollegeApp.Controllers
{
    public class SubjectController : Controller
    {
        private readonly AppDbContext _db;

        public SubjectController(AppDbContext db)
        {
            _db = db;
        }
       

        public async Task<IActionResult> Index()
        {
            var subjects = _db.Subjects
                .Include(c => c.Course)
                .Include(t => t.Teacher)
                .AsNoTracking();
            return View(await subjects.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _db.Subjects

                .Include(c => c.Course)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == id);

            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        //GET
        public IActionResult Create()
        {
            PopulateCoursesDropDownList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
        [Bind("SubjectTitle,CourseId")] Subject obj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _db.Add(obj);
                    await _db.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException  /* ex */ )
            {
                //Log the error (uncomment ex variable name and write a log.
                ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists " +
                    "see your system administrator.");
            }
            PopulateCoursesDropDownList(obj.CourseId);
            return View(obj);
        }



        //GET
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _db.Subjects
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null)
            {
                return NotFound();
            }
            PopulateCoursesDropDownList(subject.CourseId);
            return View(subject);
        }

        //POST
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subjectToUpdate = await _db.Subjects
                .FirstOrDefaultAsync(c => c.Id == id);

            if (await TryUpdateModelAsync<Subject>(subjectToUpdate,
                "",
                c => c.SubjectTitle, c => c.Teacher, c => c.CourseId))
            {
                try
                {
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateException /* ex */)
                {
                    //Log the error (uncomment ex variable name and write a log.)
                    ModelState.AddModelError("", "Unable to save changes. " +
                        "Try again, and if the problem persists, " +
                        "see your system administrator.");
                }
                return RedirectToAction(nameof(Index));
            }
            PopulateCoursesDropDownList(subjectToUpdate.CourseId);
            return View(subjectToUpdate);
        }



        //GET
        public async Task<IActionResult> Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _db.Subjects
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null)
            {
                return NotFound();
            }

            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] =
                    "Delete failed. Try again, and if the problem persists " +
                    "see your system administrator.";
            }

            return View(subject);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var subject = await _db.Subjects.FindAsync(id);
            if (subject == null)
            {
                return RedirectToAction(nameof(Index));
            }

            try
            {
                _db.Subjects.Remove(subject);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException /* ex */)
            {
                //Log the error (uncomment ex variable name and write a log.)
                return RedirectToAction(nameof(Delete), new { id = id, saveChangesError = true });
            }
        }

        

        private void PopulateCoursesDropDownList(object? selectedCourse = null)
        {
            var coursesQuery = from d in _db.Courses
                                   orderby d.Title 
                                   select d;
            ViewBag.CourseId = new SelectList(coursesQuery.AsNoTracking(), "Id", "Title", selectedCourse);
        }
    }
}

CollegeApp/Views/Subject/Details.cshtml
@model Subject

@{
    ViewData["Title"] = "Details";
}

<h2>@Html.DisplayFor(model => model.SubjectTitle)</h2>


<div>
    <h4>Subject</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SubjectTitle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SubjectTitle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(modelItem => modelItem.Course.Title)
        </dd>
    </dl>
    
    <form asp-controller="Subject" asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

CollegeApp/Views/Subject/Index.cshtml
@model IEnumerable<CollegeApp.Models.Subject>

@{
    ViewData["Title"] = "Subjects";
}

<h2>Subjects</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubjectTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Teacher)
            </th>
           
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SubjectTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Course.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Teacher.TeacherName)
                </td>
                
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-controller="Subject" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

CollegeApp/Views/Subject/create.cshtml
@{
    ViewData["Title"] = "Create";
}

@model Subject


<form method="post" action="">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Create Subject
            </h2>
            <div asp-validation-summary="All"></div>
            <div class="mb-3">
                <label asp-for="SubjectTitle">Subject Name</label>
                <input asp-for="SubjectTitle" type="text" class="form-control" />
                <span asp-validation-for="SubjectTitle" class="text-danger"></span>
            </div>
            
            
            <div class="form-group mb-3">
                <label asp-for="CourseId" class="control-label">Course</label>
                <select asp-for="CourseId" class="form-control" asp-items="ViewBag.CourseId">
                    <option value="">-- Select Course --</option>
                </select>
                <span asp-validation-for="CourseId" class="text-danger" />
            </div>
            <button type="submit" class="btn btn-primary" style="width:150px;">Add Subject</button>
            <a asp-controller="Subject" asp-action="Index" class="btn btn-secondary" style="width:150px;">Back to List</a>
        </div>
    </div>
</form>






@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    
}

CollegeApp/Views/Subject/delete.cshtml
@model Subject

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Subject</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SubjectTitle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SubjectTitle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Course.Title)
        </dd>
    </dl>
    
    <form asp-controller="Subject" method="post">
        <input asp-for="Id" hidden />
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

CollegeApp/Views/Subject/edit.cshtml
@{
    ViewData["Title"] = "Edit";
}

@model Subject

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Edit Subject
            </h2>
            <div asp-validation-summary="All"></div>
            <div class="mb-3">
                <label asp-for="SubjectTitle"></label>
                <input asp-for="SubjectTitle" type="text" class="form-control" />
                <span asp-validation-for="SubjectTitle" class="text-danger"></span>
            </div>
           
            <div class="form-group mb-3">
                <label asp-for="CourseId" class="control-label">Course</label>
                <select asp-for="CourseId" class="form-control" asp-items="ViewBag.CourseId">
                    <option value="">-- Select Course --</option>
                </select>
                <span asp-validation-for="CourseId" class="text-danger" />
            </div>
            <button type="submit" class="btn btn-primary" style="width:150px;">Update Subject</button>
            <a asp-controller="Subject" asp-action="Index" class="btn btn-secondary" style="width:150px;">Back to List</a>
        </div>
    </div>
</form>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    
}